# Generated by Django 4.1.1 on 2022-10-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="environment",
            name="team_default_true_unique_together",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="default",
        ),
    ]
