# Generated by Django 4.1.1 on 2022-10-26 18:29

import uuid

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0016_alter_crontabschedule_timezone"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "parameters",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crontab_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.crontabschedule",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.environment",
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.function"
                    ),
                ),
            ],
            bases=(core.models.mixins.ModelSaveHookMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["environment", "function"], name="s_task_environment_function"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["environment", "creator"], name="s_task_environment_creator"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["environment", "created_at"],
                name="s_task_environment_created_at",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledtask",
            index=models.Index(
                fields=["environment", "updated_at"],
                name="s_task_environment_updated_at",
            ),
        ),
    ]
