# Generated by Django 4.1.1 on 2022-10-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_environment_team_default_true_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="function",
            name="output_format",
        ),
        migrations.RemoveField(
            model_name="task",
            name="output_format",
        ),
    ]
