# Generated by Django 4.1.1 on 2022-10-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0016_alter_crontabschedule_timezone"),
        ("core", "0002_scheduledtask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("ERROR", "Error"),
                    ("ARCHIVED", "Archived"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="scheduled_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.scheduledtask",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledtask",
            name="crontab_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="django_celery_beat.crontabschedule",
            ),
        ),
    ]
