# Generated by Django 4.1.1 on 2022-11-03 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0016_alter_crontabschedule_timezone"),
        ("core", "0003_scheduledtask_status_task_scheduled_task_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledtask",
            name="crontab_schedule",
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="periodic_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
