# Generated by Django 4.1.1 on 2022-11-01 18:56

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.models.function


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_function_output_format_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="variables",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                validators=[core.models.function.list_of_strings],
            ),
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid variable name. Characters must be in [A-Z0-9_]",
                                regex="[A-Z_][A-Z0-9_]*",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(null=True)),
                ("value", models.TextField(max_length=32767)),
                ("protect", models.BooleanField(default=False)),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vars",
                        to="core.environment",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vars",
                        to="core.team",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="variable",
            constraint=models.UniqueConstraint(
                fields=("environment", "name"),
                name="environment_variable_name_unique_together",
            ),
        ),
        migrations.AddConstraint(
            model_name="variable",
            constraint=models.UniqueConstraint(
                fields=("team", "name"), name="team_variable_name_unique_together"
            ),
        ),
        migrations.AddConstraint(
            model_name="variable",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("environment__isnull", False), ("team__isnull", True)),
                    models.Q(("environment__isnull", True), ("team__isnull", False)),
                    _connector="OR",
                ),
                name="variable_only_one_team_or_environment",
            ),
        ),
    ]
