# Generated by Django 4.1.1 on 2022-11-03 12:30

from django.db import migrations, models

import core.models.function


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_function_variables_variable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="function",
            name="variables",
            field=models.JSONField(
                default=list, validators=[core.models.function.list_of_strings]
            ),
        ),
    ]
