# Generated by Django 4.1.3 on 2022-12-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_workflow_workflowrun_alter_variable_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentuserrole",
            name="inherited",
            field=models.BooleanField(default=True),
        ),
    ]
