# Generated by Django 4.1.3 on 2022-12-30 15:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_workflow_workflowrun_alter_variable_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid parameter name. Only numbers, letters, and underscore are allowed.",
                                regex="^\\w+$",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parameter_type",
                    models.CharField(
                        choices=[
                            ("integer", "integer"),
                            ("string", "string"),
                            ("text", "text"),
                            ("float", "float"),
                            ("boolean", "boolean"),
                            ("date", "date"),
                            ("datetime", "datetime"),
                            ("json", "json"),
                        ],
                        max_length=64,
                    ),
                ),
                ("default", models.CharField(blank=True, max_length=128, null=True)),
                ("required", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="workflowstep",
            name="ws_workflow_next_unique_together",
        ),
        migrations.RemoveField(
            model_name="workflow",
            name="schema",
        ),
        migrations.AlterField(
            model_name="workflowrunstep",
            name="workflow_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.workflowstep",
            ),
        ),
        migrations.AddField(
            model_name="workflowparameter",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="core.workflow",
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowparameter",
            constraint=models.UniqueConstraint(
                fields=("workflow", "name"), name="wp_workflow_name_unique"
            ),
        ),
    ]
