# (required): schema version for the package portion of the yaml. This would inform which serializer / parser
# to use in the event that we needed to make breaking changes to the way packages are defined.
version: 1.0
package:
  # (required) human-friendly unique identifier (team + package name must be unique)
  name: calculator

  # (optional) Summary of the packages purpose
  summary: Simple calculator example package

  # (optional) Detailed description
  description:
    The calculator package contains many functions useful for calculating
    values. One of these functions is production ready.

  # (required) Language that the functions are written in
  language: python

  # (required)
  functions:
    # Similar to package level fields, but for the function
    - name: add
      summary: Add two integers
      description: This function consumes two integers and outputs the sum.
      return_type: integer

      # (required) Parameters that the function takes
      parameters:
        - name: a
          type: integer
          default: 1
          required: true
        - name: b
          type: integer
          default: 1
          required: true
