from allauth.account.adapter import DefaultAccountAdapter


class FunctionaryAccountAdapter(DefaultAccountAdapter):
    """This adapter disables local account creation and messaging.

    Account creation via third party auth provider is still enabled
    but local creation is not. The messages generated by allauth are
    not very useful for our case and are not able to be turned off
    otherwise."""

    def is_open_for_signup(self, request):
        """Signups are disabled"""
        return False

    def add_message(self, *args, **kwargs):
        """No messages will be sent to django.contrib.messages"""
        pass
